# NB: don't set `language: haskell` here

env:
 - GHCVER=7.8.4 CABALVER=1.18
 - GHCVER=7.10.1 CABALVER=1.22


# Note: the distinction between `before_install` and `install` is not
#       important.
before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"

install:
 - travis_retry cabal update
 - cabal install --only-dependencies --enable-tests

script:
 # -v2 provides useful information for debugging
 - cabal configure -v2 --enable-tests

 # this builds all libraries and executables
 # (including tests/benchmarks)
 - cabal build
 - cabal test

 # tests that a source-distribution can be generated
 - cabal sdist

 # check that the generated source-distribution can be built & installed
 - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      cabal install --force-reinstalls "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.8.4
    - ghc-7.10.1
    - cabal-install-1.18
    - cabal-install-1.22
